name: Assembly and deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15

    - name: Assembly
      run: sbt assembly

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      if: ${{ success() }}
      with:
        name: GitHubActionsTest
        path: ./target/build/GitHubActionsTest.jar
        
    - name: Exports SSH private key
      if: ${{ success() }}
      run: echo "$SSH_PRIVATE_KEY" > id_rsa && chmod 600 id_rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  
    - name: Scp deploy
      if: ${{ success() }}
      run: scp -o 'StrictHostKeyChecking no' -o UserKnownHostsFile=/dev/null -P ${{ secrets.SSH_PORT }} -i id_rsa ./target/build/GitHubActionsTest.jar ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.SCP_TARGET }}
